CREATE DATABASE spring;
use spring;
CREATE TABLE IF NOT EXISTS User(
  userId INT(6) AUTO_INCREMENT PRIMARY KEY,
  userName VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  status INT NOT NULL,
  createdDate DATE
);

CREATE TABLE IF NOT EXISTS Role(
  roleId INT(6) AUTO_INCREMENT PRIMARY KEY,
  roleName VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS User_Role(
  userRoleId INT(6) AUTO_INCREMENT PRIMARY KEY,
  userId INT(6) NOT NULl,
  roleId INT(6) NOT NULL,
  CONSTRAINT FK_UserRole_User FOREIGN KEY (userId) REFERENCES User(userId),
  CONSTRAINT FK_UserRole_Role FOREIGN KEY (roleId) REFERENCES Role(roleId)
);
